apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postapi-kubernetes
  labels:
    app: postapi-kuberentes-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
     app: postapi-kuberentes-pod
  template:
    metadata:
      labels:
        app: postapi-kuberentes-pod
    spec:
      containers:
      - name: postapi-kubernetes-containers
        image: "postapi:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        volumeMounts:
          - name: appsettings
            mountPath: /app/appsettings.json #而我们这里只要覆盖 appsettings.json，而非整个 /app 目录，所以要加上具体的文件名后缀，如：/app/[文件名]
            subPath: appsettings.json #同时用 subPath 告知这个就是我们的文件 https://github.com/kubernetes/kubernetes/issues/44815#issuecomment-297077509
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ASPNETCORE_ENVIRONMENT
          value: "kubernetes"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
        - name: appsettings
          configMap:
            name: postapi-appsettings-v1
            items:
            - key: appsettings.json
              path: appsettings.json

---
#apiVersion: v1
#kind: Service
#metadata: 
#  name: postapi-service
#spec:
#  clusterIP: None
#  selector:
#    app: postapi-kuberentes-pod
#  ports:
#    - protocol: TCP
#      port: 5001 
