FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 55392
EXPOSE 44337

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["PersonalPortal/src/ApiGateways/OcelotApiGw/OcelotApiGw.csproj", "PersonalPortal/src/ApiGateways/OcelotApiGw/"]
RUN dotnet restore "PersonalPortal/src/ApiGateways/OcelotApiGw/OcelotApiGw.csproj"
COPY . .
WORKDIR "/src/PersonalPortal/src/ApiGateways/OcelotApiGw"
RUN dotnet build "OcelotApiGw.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "OcelotApiGw.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "OcelotApiGw.dll"]